---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: syndesis-operator
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: operator
    syndesis.io/component: syndesis-operator
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: syndesis-operator
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: operator
    syndesis.io/component: syndesis-operator
rules:
- apiGroups:
  - syndesis.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - "*"
- apiGroups:
  - template.openshift.io
  resources:
  - processedtemplates
  verbs:
  - "create"
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - "*"
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - "*"
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - "*"
- apiGroups:
  - build.openshift.io
  resources:
  - buildconfigs
  verbs:
  - "*"
- apiGroups:
  - authorization.openshift.io
  resources:
  - rolebindings
  verbs:
  - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: syndesis-operator:install
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: operator
    syndesis.io/component: syndesis-operator
subjects:
- kind: ServiceAccount
  name: syndesis-operator
roleRef:
  kind: Role
  name: syndesis-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: v1
metadata:
  name: syndesis-operator:view
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: operator
    syndesis.io/component: syndesis-operator
subjects:
- kind: ServiceAccount
  name: syndesis-operator
roleRef:
  name: view
---
kind: RoleBinding
apiVersion: v1
metadata:
  name: syndesis-operator:edit
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: operator
    syndesis.io/component: syndesis-operator
subjects:
- kind: ServiceAccount
  name: syndesis-operator
roleRef:
  name: edit
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: syndesis-operator
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/type: operator
    syndesis.io/component: syndesis-operator
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
      syndesis.io/app: syndesis
      syndesis.io/type: operator
      syndesis.io/component: syndesis-operator
  template:
    metadata:
      labels:
        syndesis.io/app: syndesis
        syndesis.io/type: operator
        syndesis.io/component: syndesis-operator
    spec:
      serviceAccountName: syndesis-operator
      containers:
        - name: syndesis-operator
          image: syndesis/syndesis-operator
          command:
          - syndesis-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
